--- 
addons: 
  apt: 
    packages: 
      - g++
      - build-essential
before_deploy: 
  - "ls -ld ."
  - "ls -ld bin"
cache: ~
deploy: 
  cleanup: false
  draft: true
  file_glob: true
  file: 
    - bin/*
  file_glob: true
  provider: releases
  skip_cleanup: true
  token: $github_token
dist: bionic
language: cpp
os: linux
script: 
  - make
